######################################################################
# Automatically generated by qmake (2.01a) Fri Feb 11 00:04:32 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += RSort.h
SOURCES += RSort.cpp

# QT += qt3support

INCPATH += ../../../../dc2/include ../../../../rm/include
LIBS += -L../../../../rm/lib -L../../../../dc2/lib -ldc -lrm -lelf -lm -ldisasm