######################################################################
# Automatically generated by qmake (2.01a) Tue Feb 15 14:56:57 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += ROthello.h
SOURCES += ROthello.cpp

# manually added
INCPATH += ../../../../dc2/include ../../../../rm/include
LIBS += -L../../../../rm/lib -L../../../../dc2/lib -ldc-profile -lrm -lelf -lm -ldisasm

