######################################################################
# Automatically generated by qmake (2.01a) Tue Feb 15 14:01:05 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Othello.h
SOURCES += Othello.cpp

# manually added
INCPATH += ../../../../dc2/include ../../../../rm/include
LIBS += -L../../../../rm/lib -L../../../../dc2/lib -ldc -lrm -lelf -lm -ldisasm