######################################################################
# Automatically generated by qmake (2.01a) Thu Feb 10 22:52:45 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += ROthello2.h
SOURCES += ROthello2.cpp

# manually added

# QT += qt3support

INCPATH += ../../../../dc2/include ../../../../rm/include
LIBS += -L../../../../rm/lib -L../../../../dc2/lib -ldc-profile -lrm -lelf -lm -ldisasm