######################################################################
# Automatically generated by qmake (2.01a) Thu Feb 24 12:21:56 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += ButtonGrid2.h
SOURCES += ButtonGrid2.cpp

# manually added
INCPATH += ../../../../dc2/include ../../../../rm/include
LIBS += -L../../../../rm/lib -L../../../../dc2/lib -ldc -lrm -lelf -lm -ldisasm
